import json
from pathlib import Path
import pickle
import random

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


FEATURE_ORDER = [
    "age",
    "sex",
    "cp",
    "trestbps",
    "chol",
    "fbs",
    "restecg",
    "thalach",
    "exang",
    "oldpeak",
    "slope",
    "ca",
    "thal",
]


def clamp(value, minimum, maximum):
    return max(minimum, min(maximum, value))


def synthetic_patient():
    age = random.randint(29, 77)
    sex = random.randint(0, 1)
    cp = random.choices([0, 1, 2, 3], weights=[35, 20, 25, 20])[0]
    trestbps = int(clamp(random.gauss(130, 18), 90, 210))
    chol = int(clamp(random.gauss(235, 45), 130, 420))
    fbs = 1 if random.random() < 0.18 else 0
    restecg = random.choices([0, 1, 2], weights=[55, 35, 10])[0]
    thalach = int(clamp(random.gauss(165 - age * 0.45, 18), 75, 205))
    exang = 1 if random.random() < 0.28 else 0
    oldpeak = round(clamp(random.gauss(0.9, 0.9), 0, 5.8), 1)
    slope = random.choices([0, 1, 2], weights=[45, 35, 20])[0]
    ca = random.choices([0, 1, 2, 3, 4], weights=[55, 22, 13, 7, 3])[0]
    thal = random.choices([0, 1, 2, 3], weights=[30, 18, 42, 10])[0]

    features = [
        age,
        sex,
        cp,
        trestbps,
        chol,
        fbs,
        restecg,
        thalach,
        exang,
        oldpeak,
        slope,
        ca,
        thal,
    ]

    risk_score = -4.0
    risk_score += (age - 50) * 0.035
    risk_score += 0.35 if sex == 1 else 0
    risk_score += [0.45, 0.2, -0.15, 0.65][cp]
    risk_score += (trestbps - 120) * 0.012
    risk_score += (chol - 200) * 0.006
    risk_score += 0.35 if fbs == 1 else 0
    risk_score += 0.2 if restecg > 0 else 0
    risk_score += (145 - thalach) * 0.018
    risk_score += 0.8 if exang == 1 else 0
    risk_score += oldpeak * 0.45
    risk_score += [0, 0.45, 0.75][slope]
    risk_score += ca * 0.55
    risk_score += [0, 0.35, 0.5, 0.25][thal]
    risk_score += random.gauss(0, 0.9)

    label = 1 if risk_score > 0 else 0
    return features, label


def main():
    random.seed(42)
    rows = []
    labels = []

    for _ in range(1200):
        features, label = synthetic_patient()
        rows.append(features)
        labels.append(label)

    x_train, x_test, y_train, y_test = train_test_split(
        rows,
        labels,
        test_size=0.2,
        random_state=42,
        stratify=labels,
    )

    scaler = StandardScaler()
    x_train_scaled = scaler.fit_transform(x_train)
    x_test_scaled = scaler.transform(x_test)

    model = RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        max_depth=5,
        min_samples_split=10,
    )
    model.fit(x_train_scaled, y_train)

    predictions = model.predict(x_test_scaled)
    probabilities = model.predict_proba(x_test_scaled)[:, 1]

    output_dir = Path("model")
    output_dir.mkdir(exist_ok=True)

    with (output_dir / "model.pkl").open("wb") as model_file:
        pickle.dump(model, model_file)

    with (output_dir / "scaler.pkl").open("wb") as scaler_file:
        pickle.dump(scaler, scaler_file)

    metadata = {
        "mode": "demo",
        "source": "Synthetic data generated by scripts/generate_demo_model.py",
        "warning": "This model is only for app development and deployment testing. It is not medically valid.",
        "featureOrder": FEATURE_ORDER,
        "sklearnVersion": "1.8.0",
        "holdoutAccuracy": round(accuracy_score(y_test, predictions), 3),
        "holdoutRocAuc": round(roc_auc_score(y_test, probabilities), 3),
    }

    with (output_dir / "demo_model.json").open("w", encoding="utf-8") as metadata_file:
        json.dump(metadata, metadata_file, indent=2)

    print("Generated demo artifacts:")
    print(f"- {output_dir / 'model.pkl'}")
    print(f"- {output_dir / 'scaler.pkl'}")
    print(f"- {output_dir / 'demo_model.json'}")
    print(f"Holdout accuracy: {metadata['holdoutAccuracy']:.3f}")
    print(f"Holdout ROC AUC: {metadata['holdoutRocAuc']:.3f}")
    print("Warning: this is a synthetic demo model, not a medical model.")


if __name__ == "__main__":
    main()
